# config.yaml
experiment:
  seed: 42
  name: "SMM4H-2025-VAEM-Detection"

data:
  train_path: "data/train.csv"
  test_path: "data/valid.csv"
  augmentation: true

model:
  name: "allenai/biomed_roberta_base"
  dropout: 0.3

training:
  k_folds: 5
  epochs: 10
  batch_size: 8
  learning_rate: 2e-5
  weight_decay: 0.01

logging:
  log_file: "experiment.log"
  level: "INFO"

loss:
  alpha: 0.33  # Cross-entropy
  beta: 0.33   # Focal loss
  gamma: 0.33  # Dice loss

evaluation:
  beta: 1.3