_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
                - 105
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.8
            "6": 4.50.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
        visualize:
            overall_confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Overall Confusion Matrix (Dev Set)
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: overall_confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
decision_threshold:
    value: 0.3
dev_csv:
    value: data/dev_data_SMM4H_2025_Task_1.csv
device:
    value: cuda
e5_model_name:
    value: intfloat/multilingual-e5-large
oversampling:
    value: RandomOverSampler
oversampling_applied:
    value: true
random_state:
    value: 42
rf_max_depth:
    value: null
rf_min_samples_leaf:
    value: 2
rf_min_samples_split:
    value: 5
rf_n_estimators:
    value: 150
train_csv:
    value: data/train_data_SMM4H_2025_Task_1.csv
