_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 105
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.12.2
            "5": 0.19.8
            "6": 4.50.0
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
max_length:
    value: 256
simcse_batch_size:
    value: 16
simcse_epochs:
    value: 1
simcse_lr:
    value: 3e-05
simcse_model:
    value: xlm-roberta-base
simcse_pooling:
    value: mean
simcse_temp:
    value: 0.05
simcse_warmup_ratio:
    value: 0.06
